version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - users-api
    environment:
      - NEXT_PUBLIC_API_URL=http://users-api:8080

  users-api:
    build: ./users-api
    ports:
      - '8080:8080'
